### ISSUE TITLE
Debian OS

### ISSUE THREAD

**Issue by kenbrill** [esimonetti/DabianDockerMac#1]
I was trying to use this as per your instructions but my Database is 25G.  So I created a second hard drive (EXT3 and EXT4 tried) and mounted it to /home and created a 'docker' directory.  That all worked and so my home directory was 200G.

I then tried to copy over my 25G sql file and it makes it to 3G or so and then it fails and the OS barfs.  I tried every trick in google but so far no luck.  Do you know of anything that might be causing this?

**Comment by esimonetti** [comment]
Hi Ken,

Might it be some permission issues?
Be really careful at manually moving/changing permissions/ownership of the data directories, as they use the guids of the docker container running MySQL.

I found it useful to run the command rsync -a --numeric-ids as root, as it preservers permissions and ownerships as they are.

I have not attempted to load a 25GB SQL database on it, but I was able to start a previously working container without issues following the steps below to add a 100GB disk to the virtualbox vm:

1. Stop running SugarDockerized stack and shutdown virtualbox vm
2. Add a new disk to the vm
3. Start the virtualbox vm
4. ssh into the box
5. sudo fdisk -l
    1. Identified new disk as "/dev/sdb"
    2. sudo cfdisk /dev/sdb
    3. Create linux partition type 83
    4. Exit
    5. sudo fdisk -l
    6. Identified partition "/dev/sdb1"
6. If wanting to leverage xfs (normally suitable for MySQL databases)
    1. sudo apt-get install xfsprogs
    2. sudo mkfs.xfs -f /dev/sdb1
7. cd /home
8. sudo mv docker docker1
9. sudo mkdir docker
10. sudo chown docker:docker docker
11. sudo vi /etc/fstab
    1. Add the following line
    2. /dev/sdb1  /home/docker xfs  defaults  0  0
    3. Save and exit
12. sudo mount --all
13. df -h
    1. Verify that /dev/sdb1 is now mounted on /home/docker
14. cd docker1
15. sudo rsync -av --numeric-ids . ../docker/
16. Start SugarDockerized
17. Once confirmed working even after a reboot, wipe /home/docker1

See if this helps
Cheers
